# Generated by Django 3.2.9 on 2022-03-07 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profile1.jpeg', null=True, upload_to='')),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Student Name')),
                ('age', models.CharField(max_length=60, verbose_name='student age')),
                ('place_birth', models.CharField(max_length=180, verbose_name='place of birth')),
                ('gender', models.CharField(max_length=80, verbose_name='gender')),
                ('clases', models.CharField(max_length=60, verbose_name='class')),
                ('school', models.CharField(max_length=90, null=True, verbose_name='school')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('parent_name', models.CharField(max_length=180, verbose_name='parent Name')),
                ('phone_number', models.CharField(max_length=60, verbose_name='contact phone')),
                ('account_number', models.CharField(max_length=60, verbose_name='acoount number')),
                ('parent_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone', models.CharField(blank=True, max_length=180, null=True, verbose_name='Student Name')),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agoon.customer')),
            ],
        ),
    ]
