# Generated by Django 3.2.9 on 2022-03-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoon', '0004_auto_20220314_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreport',
            name='clases',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='s_points',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='s_year',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='statues',
        ),
        migrations.AddField(
            model_name='studentreport',
            name='Arabic',
            field=models.IntegerField(blank=True, null=True, verbose_name='Arabic Subject'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='Biology',
            field=models.IntegerField(blank=True, null=True, verbose_name='Biology Subject'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='Business',
            field=models.IntegerField(blank=True, null=True, verbose_name='Business Subject'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='Chemistry',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chemistry Subject'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='English',
            field=models.IntegerField(blank=True, null=True, verbose_name='IRE Subject'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='Geogrphy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Geogrphy Subject'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='History',
            field=models.IntegerField(blank=True, null=True, verbose_name='History Subject'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='ICT',
            field=models.IntegerField(blank=True, null=True, verbose_name='ICT Subject'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='IRE',
            field=models.IntegerField(blank=True, null=True, verbose_name='IRE Subject'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='Math',
            field=models.IntegerField(blank=True, null=True, verbose_name='Math Subject'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='Physics',
            field=models.IntegerField(blank=True, null=True, verbose_name='physics Subject'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='Quran',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quran Subject'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='Somali',
            field=models.IntegerField(blank=True, null=True, verbose_name='Somali Subject'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='head_teacher',
            field=models.CharField(max_length=200, null=True, verbose_name='Head Teacher name'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='school_name',
            field=models.CharField(max_length=200, null=True, verbose_name='school name'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='yearly',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='age',
            field=models.IntegerField(verbose_name='student age'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Student name'),
        ),
    ]
