# Generated by Django 4.0.3 on 2022-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoon', '0007_auto_20220318_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='age',
            field=models.CharField(max_length=20, verbose_name='student age'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Arabic',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Arabic Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Arabic_Mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mid Term Arabic Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Biology',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Biology Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Biology_Mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mid Term Biology Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Business',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Business Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Business_Mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mid Term Business Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Chemistry',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Chemistry Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Chemistry_Mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mid Term Chemistry Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='English',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final English Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='English_Mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mid Term English Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Geogrphy',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Geogrphy Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Geogrphy_Mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mid Term Geogrphy Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='History',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final History Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='History_Mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mid Term History Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='ICT',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final ICT Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='ICT_Mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mid Term ICT Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='IRE',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final IRE Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='IRE_Mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mid Term IRE Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Math',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Math Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Math_Mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mid Term Math Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Physics',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Physics Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Physics_Mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mid Term Physics Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Quran',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Quran '),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Somali',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Somali Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Somali_Mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mid Term Somali Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Total',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Total Marks'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='Total_Mid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MidTerm Total Marks'),
        ),
    ]
